name: repel
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: "3.3.4"

dependencies:
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  firebase_storage: ^11.7.2
  fl_chart: ^0.67.0
  flutter:
    sdk: "flutter"
  google_fonts: ^6.2.1
  image_picker: ^1.1.0
  intl: ^0.19.0
  responsive_framework: ^0.2.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
